twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'Form/bootstrap_3_layout.html.twig'
        - '@VichUploader/Form/fields.html.twig'
        - '@GregwarCaptcha/captcha.html.twig'

when@test:
    twig:
        strict_variables: true
